{
 "title": "AIGC workload Power Consumption Dashboard",
 "description": "Dashboard for AMX/non-AMX AIGC workload Power Consumption comparison",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "AIGC Joule/Token (Model: Llama-2-7b-chat-hf-sharded-bf16)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (\r\n  (increase(kepler_container_package_joules_total{container_namespace=\"aigc-amx\", command=\"python\", pod_name=~\"cse-aigc-worker-amx-.*\"}[1m])\r\n  ) *\r\n  (count_over_time(kepler_container_package_joules_total{container_namespace=\"aigc-amx\", command=\"python\", pod_name=~\"cse-aigc-worker-amx-.*\"}[4m])/\r\n    count_over_time(kepler_container_package_joules_total{container_namespace=\"aigc-amx\", command=\"python\", pod_name=~\"cse-aigc-worker-amx-.*\"}[1m])\r\n  )\r\n)\r\n+\r\nsum (\r\n  (increase(kepler_container_dram_joules_total{container_namespace=\"aigc-amx\", command=\"python\", pod_name=~\"cse-aigc-worker-amx-.*\"}[1m])\r\n  ) *\r\n  (count_over_time(kepler_container_dram_joules_total{container_namespace=\"aigc-amx\", command=\"python\", pod_name=~\"cse-aigc-worker-amx-.*\"}[4m])/\r\n    count_over_time(kepler_container_dram_joules_total{container_namespace=\"aigc-amx\", command=\"python\", pod_name=~\"cse-aigc-worker-amx-.*\"}[1m])\r\n  )\r\n)) / (sum(model_inference_tokens_per_second{job=\"cse-aigc-worker-amx\"} > 0 ) * 60 * 4)",
     "legendFormat": "Inference with AMX accelerator"
    },
    {
     "expr": "(sum (\r\n  (increase(kepler_container_package_joules_total{container_namespace=\"aigc-non\", command=\"python\", pod_name=~\"cse-aigc-worker-non-.*\"}[1m])\r\n  ) *\r\n  (count_over_time(kepler_container_package_joules_total{container_namespace=\"aigc-non\", command=\"python\", pod_name=~\"cse-aigc-worker-non-.*\"}[4m])/\r\n    count_over_time(kepler_container_package_joules_total{container_namespace=\"aigc-non\", command=\"python\", pod_name=~\"cse-aigc-worker-non-.*\"}[1m])\r\n  )\r\n)\r\n+\r\nsum (\r\n  (increase(kepler_container_dram_joules_total{container_namespace=\"aigc-non\", command=\"python\", pod_name=~\"cse-aigc-worker-non-.*\"}[1m])\r\n  ) *\r\n  (count_over_time(kepler_container_dram_joules_total{container_namespace=\"aigc-non\", command=\"python\", pod_name=~\"cse-aigc-worker-non-.*\"}[4m])/\r\n    count_over_time(kepler_container_dram_joules_total{container_namespace=\"aigc-non\", command=\"python\", pod_name=~\"cse-aigc-worker-non-.*\"}[1m])\r\n  )\r\n)) / (sum(model_inference_tokens_per_second{job=\"cse-aigc-worker-non\"} > 0 ) * 60 * 4)",
     "legendFormat": "Inference without AMX accelerator"
    }
   ]
  },
  {
   "title": "AIGC Performance (Token/Second)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "model_inference_tokens_per_second{job=\"cse-aigc-worker-non\"}",
     "legendFormat": "Non-AMX"
    },
    {
     "expr": "model_inference_tokens_per_second{job=\"cse-aigc-worker-amx\"}",
     "legendFormat": "AMX"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "options": {
    "content": "## AMX Accelerate Cloud Native AIGC Pipeline\n\n- The microservices (AMX or AVX2) were orchestrated on two SPR server node.\n- Comparision Macro Bench: Joule Per Token - Power Consumption for each token generated\n- Micro Benches:\n  - Performance: Tokens Per Second\n  - Power: Joule, collected by Kepler for container"
   }
  },
  { "title": "Power Consumption (Watt)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "datasource" },
  {
   "title": "AIGC Containers Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(kepler_container_package_joules_total{container_namespace=~\"aigc-non\"}[1m])) + sum(irate(kepler_container_dram_joules_total{container_namespace=~\"aigc-non\"}[1m]))",
     "legendFormat": "Non-AMX"
    },
    {
     "expr": "sum(irate(kepler_container_package_joules_total{container_namespace=~\"aigc-amx\"}[1m])) + sum(irate(kepler_container_dram_joules_total{container_namespace=~\"aigc-amx\"}[1m]))",
     "legendFormat": "AMX"
    }
   ]
  },
  {
   "title": "Node Total Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(kepler_node_package_joules_total{exported_instance=~\"demo-quantagrid-d54q-2u-worker\"}[1m])) + sum(irate(kepler_node_dram_joules_total{exported_instance=~\"demo-quantagrid-d54q-2u-worker\"}[1m]))",
     "legendFormat": "Non-AMX"
    },
    {
     "expr": "sum(irate(kepler_node_package_joules_total{exported_instance=~\"demo-quantagrid-d54q-2u\"}[1m])) + sum(irate(kepler_node_dram_joules_total{exported_instance=~\"demo-quantagrid-d54q-2u\"}[1m]))",
     "legendFormat": "AMX"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_scaling_frequency_hertz{instance=~\"demo-quantagrid-d54q-2u-worker\"}[1m]) * 100)",
     "legendFormat": "Non-AMX"
    },
    {
     "expr": "avg(irate(node_cpu_scaling_frequency_hertz{instance=~\"demo-quantagrid-d54q-2u\"}[1m])* 100)",
     "legendFormat": "AMX"
    }
   ]
  },
  {
   "title": "CPU Load (used vCPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "instance:node_cpu:rate:sum{instance=~\"demo-quantagrid-d54q-2u-worker\"}",
     "legendFormat": "Non-AMX"
    },
    {
     "expr": "instance:node_cpu:rate:sum{instance=~\"demo-quantagrid-d54q-2u\"}",
     "legendFormat": "AMX"
    }
   ]
  },
  { "title": "Power Consumption (Detail)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total Power Consumption (W) in Namespace: aigc-non",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(irate(kepler_container_package_joules_total{container_namespace=~\"aigc-non\"}[1m]))",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(irate(kepler_container_dram_joules_total{container_namespace=~\"aigc-non\"}[1m]))",
     "legendFormat": "DRAM"
    }
   ]
  },
  {
   "title": "Total Power Consumption (W) in Namespace: aigc-amx",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(irate(kepler_container_package_joules_total{container_namespace=~\"aigc-amx\"}[1m]))",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(irate(kepler_container_dram_joules_total{container_namespace=~\"aigc-non\"}[1m]))",
     "legendFormat": "DRAM"
    }
   ]
  }
 ]
}