apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastchat-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastchat-api-server
  template:
    metadata:
      labels:
        app: fastchat-api-server
    spec:
      containers:
      - name: fastchat-api-server
        image: bluewish/cnagc-fastchat-k8s:latest
        ports:
        - containerPort: 8000
        command: ["python3.9", "-m", "fastchat.serve.openai_api_server", "--controller-address", "http://fastchat-controller:21001", "--host", "0.0.0.0", "--port", "8000"]

---
apiVersion: v1
kind: Service
metadata:
  name: fastchat-api-server
spec:
  type: NodePort
  selector:
    app: fastchat-api-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31008

