apiVersion: apps/v1
kind: Deployment
metadata:
  name: cse-aigc-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cse-aigc-web-ui
  template:
    metadata:
      labels:
        app: cse-aigc-web-ui
    spec:
      containers:
      - name: cse-aigc-web-ui
        image: gar-registry.caas.intel.com/cpio/cnagc-fastchat-k8s:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        command: ["/home/ubuntu/entrypoint.sh"]
        env:
        - name: DEPLOY_TYPE
          value: "ui"
        - name: FASTCHAT_ROOT
          value: "/home/ubuntu/fastchat"
        - name: CONTROLLER_SVC
          value: cse-aigc-controller

---
apiVersion: v1
kind: Service
metadata:
  name: cse-aigc-web-ui
spec:
  type: NodePort
  selector:
    app: cse-aigc-web-ui
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 31009

