apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cse-aigc-worker-non
  namespace: non
  labels:
    service-monitor: cse-aigc-worker-non
spec:
  selector:
    matchLabels:
      app: cse-aigc-worker-non
  endpoints:
  - port: http
    interval: 15s
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cse-aigc-worker-amx
  namespace: amx
  labels:
    service-monitor: cse-aigc-worker-amx
spec:
  selector:
    matchLabels:
      app: cse-aigc-worker-amx
  endpoints:
  - port: http
    interval: 15s

