apiVersion: apps/v1
kind: Deployment
metadata:
  name: cse-aigc-model-worker-non
  namespace: non
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cse-aigc-model-worker-non
  template:
    metadata:
      labels:
        app: cse-aigc-model-worker-non
    spec:
      containers:
      - name: cse-aigc-model-worker-non
        image: gar-registry.caas.intel.com/cpio/cnagc-fastchat-k8s:latest
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 21002
          name: model
          protocol: TCP
        env:
        - name: MODEL_NAME
          value: "vicuna-7b-v1.3"
          #value: "opt-1.3b-bf16-8b-samples"
        - name: ATEN_CPU_CAPABILITY
          value: "avx2"
        - name: DEPLOY_TYPE
          value: "model"
        - name: FASTCHAT_ROOT
          value: "/fastchat"
        - name: MODEL_WORKER_SVC
          value: cse-aigc-model-worker-non.non.svc.cluster.local
        - name: MODEL_WORKER_PORT
          value: "21002"
        - name: CONTROLLER_SVC
          value: cse-aigc-controller.default.svc.cluster.local
        - name: OMP_NUM_THREADS
          value: "62"
        command: ["/entrypoint.sh"]

---
apiVersion: v1
kind: Service
metadata:
  name: cse-aigc-model-worker-non
  namespace: non
  labels:
    app: cse-aigc-model-worker-non
spec:
  selector:
    app: cse-aigc-model-worker-non
  ports:
    - protocol: TCP
      name: model
      port: 21002
      targetPort: 21002
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000

