apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastchat-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastchat-web-ui
  template:
    metadata:
      labels:
        app: fastchat-web-ui
    spec:
      containers:
      - name: fastchat-web-ui
        image: gar-registry.caas.intel.com/cpio/cnagc-fastchat-k8s:latest
        ports:
        - containerPort: 9000
        command: ["/entrypoint.sh"]
        env:
        - name: DEPLOY_TYPE
          value: "ui"
        - name: FASTCHAT_ROOT
          value: "/fastchat"

---
apiVersion: v1
kind: Service
metadata:
  name: fastchat-web-ui
spec:
  type: NodePort
  selector:
    app: fastchat-web-ui
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 31009

