apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastchat-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastchat-controller
  template:
    metadata:
      labels:
        app: fastchat-controller
    spec:
      containers:
      - name: fastchat-controller
        image: gar-registry.caas.intel.com/cpio/cnagc-fastchat-k8s:latest
        ports:
        - containerPort: 21001
        command: ["/entrypoint.sh"]
        env:
        - name: DEPLOY_TYPE
          value: "controller"
        - name: FASTCHAT_ROOT
          value: "/fastchat"
---
apiVersion: v1
kind: Service
metadata:
  name: fastchat-controller
spec:
  selector:
    app: fastchat-controller
  ports:
    - protocol: TCP
      port: 21001
      targetPort: 21001

