apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastchat-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastchat-web-ui
  template:
    metadata:
      labels:
        app: fastchat-web-ui
    spec:
      containers:
      - name: fastchat-web-ui
        image: leyao/fastchat:latest
        ports:
        - containerPort: 9000
        command: ["python3.9", "-m", "fastchat.serve.gradio_web_server", "--controller-address", "http://fastchat-controller:21001", "--host", "0.0.0.0", "--port", "9000"]

---
apiVersion: v1
kind: Service
metadata:
  name: fastchat-web-ui
spec:
  selector:
    app: fastchat-web-ui
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

