#
# This example creates 3 ConfigMaps:
#  - cri-resmgr-config.default: the default configuration
#  - cri-resmgr-config.group.foo: the configuration for nodes in group foo
#  - cri-resmgr-config.node.cl0-slave1: the configuration for node cl0-slave1
#
# You can assign nodes to group foo using the command
#   kubectl label --overwrite node $NODE_NAME cri-resource-manager.intel.com/group=foo
#
# You can remove nodes from group foo using the command
#   kubectl label node $NODE_NAME cri-resource-manager.intel.com/group-
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config.default
  namespace: kube-system
data:
  policy: |+
    Active: balloons
    AvailableResources:
      cpu: cpuset:0-63
    ReservedResources:
      cpu: cpuset:0-7
    balloons:
      PinCPU: true
      PinMemory: true
      IdleCPUClass: idle
      BalloonTypes:
      - Name: "common"
        MinCPUs: 2
        MaxCPUs: 6
        CPUClass: medium
        Namespaces:
          - "*"
      - Name: "cache"
        MinCPUs: 1
        MaxCPUs: 1
        CPUClass: low
        Namespaces:
          - "*"
      - Name: "compute"
        MinCPUs: 6
        MaxCPUs: 10
        CPUClass: high
        Namespaces:
          - "*"
      - Name: "io"
        MinCPUs: 2
        MaxCPUs: 4
        CPUClass: medium
        Namespaces:
          - "*"
  cpu: |+
    classes:
      low:
        minFreq: 800000
        maxFreq: 2000000
      medium:
        minFreq: 1000000
        maxFreq: 2600000
      high:
        minFreq: 800000
        maxFreq: 800000
  instrumentation: |+
    HTTPEndpoint: :8899
    PrometheusExport: true
  logger: |+
    Debug: resource-manager,cache,policy,message
