apiVersion: v1
kind: ServiceAccount
metadata:
  name: cri-resmgr-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cri-resmgr-agent
rules:
- apiGroups:
  - ""
  - criresmgr.intel.com
  resources:
  - nodes
  - configmaps
  - adjustments
  - labels
  - annotations
  verbs:
  - get
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cri-resmgr-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cri-resmgr-agent
subjects:
- kind: ServiceAccount
  name: cri-resmgr-agent
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cri-resmgr-agent
  name: cri-resmgr-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: cri-resmgr-agent
  template:
    metadata:
      labels:
        app: cri-resmgr-agent
    spec:
      serviceAccount: cri-resmgr-agent
      containers:
        - name: cri-resmgr-agent
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: intel/cri-resmgr-agent:v0.7.2
          imagePullPolicy: Always # for testing
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          volumeMounts:
          - name: resmgrsockets
            mountPath: /var/run/cri-resmgr
          resources:
            limits:
              cpu: 1
              memory: 512Mi
          livenessProbe:
            exec:
              command: ["/bin/cri-resmgr-agent-probe"]
            initialDelaySeconds: 5
            periodSeconds: 30
      volumes:
      - name: resmgrsockets
        hostPath:
          path: /var/run/cri-resmgr
